# Site settings
title               : تذكرتك
description         : متابعة برامج تذكرتك عن طريق متصفح الإنترنت
url                 : https://tazkrtak-admin.web.app
root-endpoint       : https://tazkrtak-api.web.app

# Build settings
markdown            : kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - debug.log
  - firebase.json
