# Site settings
title               : تذكرتك
description         : متابعة برامج تذكرتك عن طريق متصفح الإنترنت
url                 : "https://tazkrtak-admin.web.app"
root-endpoint       : "https://my-json-server.typicode.com/tazkrtak/counterfeit"

# Build settings
markdown            : kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - debug.log
  - firebase.json
